### PR TITLE
user can define custom fields

### PR DESCRIPTION
**Pull request by m-ariya**
`simulation_super` has an empty method `update_custom()` which is called in `update()` AFTER `update_powers()` and `update_relational()`, (such that we are sure that all mandatory fields are not Null first).

### CODE REVIEW

**Comment by SjoerdHilhorst** [comment]
it's good, did you already think about the default value Jasper mentioned?

**Comment by m-ariya** [comment]
Default values?  Like initial for custom fields? Could you remind me what Jasper was saying about this?

**Comment by SjoerdHilhorst** [comment]
> Default values? Like initial for custom fields? Could you remind me what Jasper was saying about this?

he mentioned wanting to put someting like ```soc: {float_mode: blabla, ..., default value: 300}``` so he doesn't have to go back and forth between subclass and env for some simple fields

**Comment by m-ariya** [comment]
Ok, gotcha, i ll try to have either another pair in the dictionary, or define it in 'battery_constants', mb?

**Comment by SjoerdHilhorst** [comment]
what you think is best

**Pull request merged**
